# A workflow that uses standard platform-dependent compilation paths etc
# and then builds with pip / setup.py on top of that.

name: pip builds 

on: 
  push:
    
  pull_request:
      
  workflow_dispatch:

jobs:
  build_with_pip:
    name: ${{matrix.os}} build with pip (${{ matrix.python-version }})

    strategy:
      fail-fast: false
      matrix:
        os: [ 'macos-latest', 'ubuntu-latest', 'windows-latest']
        python-version: ['2.7', '3.7', '3.8']
        exclude:
          - os: 'windows-latest'
            python-version: 2.7
          - os: 'windows-latest'
            python-version: 3.8

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout  
        uses: actions/checkout@v2

      - name: Cache conda
        uses: actions/cache@v1
        env:
        # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 1
        with:
          path: |
            ~/conda_pkgs_dir
            ~/.cache/pip
            ~/stripy/jupyterbook/_build
            
          key: macos-test-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('.github/workflows/resources/conda_test_environment.yml') }}

      - name: Miniconda + Cache
        uses: conda-incubator/setup-miniconda@v2
        with:
            miniconda-version: "latest"
            auto-update-conda: true
            environment-file: .github/workflows/resources/conda_test_environment.yml
            activate-environment: conda-test
            python-version: 3.7
            use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
  
      - name: Install (self)
        shell: bash -l {0}
        run: |
          pip install -e .      

      - name: Test with pytest
        shell: bash -l {0}
        run: |
          python -c 'import stripy;'
          pip install pytest
          pytest
 
          
      # - name: Install gfortran (ubuntu)
      #   if: matrix.os == 'ubuntu-latest' 
      #   run: |
      #     sudo apt-get install -y gfortran

      # - name: Install gfortran (macos)
      #   if: matrix.os == 'macos-latest' 
      #   run: |
      #     brew install gfortran
      #     brew link gfortran
      #     which gfortran
      #     ls /usr/local/bin

      # - name: Install Python dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install numpy 
      #     pip install scipy 
      #     pip install Cython
          
      # - name: Install (self)
      #   run: |
      #     pip install -e . 
          
      # - name: Test with pytest
      #   run: |
      #     python -c 'import stripy;'
      #     pip install pytest
      #     pytest


        