name: PYPI wheels macos

on: 
  release:
    types: [created, edited]
  # push:
  #   branches:
  #     - dev


jobs:
  deploy_to_pypi:
    name: ${{matrix.os}} build and deploy on pypi (${{ matrix.python-version }})

    strategy:
      fail-fast: false
      matrix:
        os: [ 'macos-latest']
        python-version: ['2.7', '3.7', '3.8']

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout  
        uses: actions/checkout@v2

      - name: Cache conda
        uses: actions/cache@v1
        env:
        # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 1
        with:
          path: |
            ~/conda_pkgs_dir
            ~/.cache/pip
            ~/stripy/jupyterbook/_build
            
          key: macos-test-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('.github/workflows/resources/conda_test_environment.yml') }}

      - name: Miniconda + Cache
        uses: conda-incubator/setup-miniconda@v2
        with:
            miniconda-version: "latest"
            auto-update-conda: true
            environment-file: .github/workflows/resources/conda_test_environment.yml
            activate-environment: conda-test
            python-version: 3.7
            use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
  
      - name: Install (self)
        shell: bash -l {0}
        run: |
          pip install -e .      

      - name: Test with pytest
        shell: bash -l {0}
        run: |
          pip install setuptools wheel twine
          pip install delocate
  
   
      - name: Build the wheel
        shell: bash -l {0}
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
  
        run: |
          python setup.py bdist_wheel 
          delocate-wheel -d -w fixed_wheels dist/*whl
          twine upload fixed_wheels/*whl  --skip-existing
